In [1]:
import numpy as np

In [2]:
li = [1,2,3]

In [3]:
np.array(li)

array([1, 2, 3])

In [4]:
type(np.array(li))

numpy.ndarray

In [5]:
np.arange(0,10) #analogous to range() in python

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0,11,10) #evenly spaced numbers within the range we provide

array([ 0.        ,  1.22222222,  2.44444444,  3.66666667,  4.88888889,
        6.11111111,  7.33333333,  8.55555556,  9.77777778, 11.        ])

In [16]:
np.random.randint(0,10,(3,3)) #the last argument is the size

array([[1, 4, 5],
       [4, 5, 0],
       [8, 3, 8]])

In [17]:
np.random.seed(101) #to fix the seed num so that the random number generated is always same

In [22]:
arr = np.random.randint(0,100,10) #getting 10 random nums as an array

In [23]:
arr

array([ 9, 77, 40,  4, 63, 40, 60, 92, 64,  5])

In [24]:
arr.mean()

45.4

In [25]:
arr.argmax() #index of max value in array

7

In [26]:
arr.reshape(2,5)

array([[ 9, 77, 40,  4, 63],
       [40, 60, 92, 64,  5]])

In [31]:
mat = np.arange(1,101).reshape(10,10)
mat

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [32]:
mat[:,0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [33]:
my_filter = mat>50

In [34]:
mat[my_filter]

array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [35]:
mat[mat>50]

array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])